services:
  db:
    image: postgres:16-alpine
    container_name: calorie_tracker_db
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER:-adonis}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-password}
      POSTGRES_DB: ${DB_DATABASE:-calorie_app}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  